# Generated by Django 5.2.7 on 2026-01-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_product_options_product_is_published_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Человекочитаемый URL (автозаполнение)",
                max_length=100,
                null=True,
                verbose_name="URL-имя",
            ),
        ),
    ]
