# Generated by Django 5.2.7 on 2026-01-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                default="",
                help_text="Человекочитаемый URL (автозаполнение)",
                max_length=100,
                unique=True,
                verbose_name="URL-имя",
            ),
            preserve_default=False,
        ),
    ]
